apiVersion: v1
data:
  runner-registration-token: amRDemFmcEpMZ0hNeExuekh0WEo=
  runner-token: ""
kind: Secret
metadata:
  creationTimestamp: "2019-08-14T05:40:29Z"
  labels:
    app: gitrunner-gitlab-runner
    chart: gitlab-runner-0.8.0-beta
    heritage: Tiller
    release: gitrunner
  name: gitrunner-gitlab-runner
  namespace: default
  resourceVersion: "19191197"
  selfLink: /api/v1/namespaces/default/secrets/gitrunner-gitlab-runner
  uid: 069ebdd2-be56-11e9-bf75-f80f41f27da1
type: Opaque
