apiVersion: v1
data:
  runner-registration-token: amRDemFmcEpMZ0hNeExuekh0WEo=
  runner-token: ""
kind: Secret
metadata:
  labels:
    app: gitrunner-gitlab-runner
    chart: gitlab-runner-0.8.0-beta
    release: gitrunner
  name: gitrunner-gitlab-runner
type: Opaque
