apiVersion: v1
kind: Service
metadata:
  name: kong-exporter
  namespace: kong
  labels:
    k8s-app: kong-ingress
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    k8s-app: kong-ingress
  ports:
  - name: api
    port: 8001
    protocol: TCP
