apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zk-exporter
  namespace: monitoring
  labels:
    k8s-app: zk-exporter
    namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - port: api
    interval: 30s
    scheme: http
  selector:
    matchLabels:
      k8s-app: zk-exporter
  namespaceSelector:
    matchNames:
    - monitoring

