kind: Service
apiVersion: v1
metadata:
  labels:
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.service.headless.name }}
  #namespace: public-service
spec:
  clusterIP: None
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  selector:
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
