kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbitmq-cluster
    type: LoadBalancer
  name: {{ .Values.service.loadbalancer.name }}
  #namespace: public-service
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  type: {{ .Values.service.loadbalancer.type }}
